config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks/new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create'
  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
  root to: 'tasks#index'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a task:</h1>

<%= form_for(@task) do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :details %>
  <%= f.text_field :details %>
  </p>

  <p>
  <%= f.label :completed %>
  <%= f.text_field :completed %>

  </p>

<p><%= f.submit %></p>


<% end %>

app/views/tasks/index.html.erb
<h1>Your TO DO list</h1>
<table>
  <% @tasks.each do |task| %>
<div class="tasks">
    <p><%= task.completed ? "v" : "x" %></p>
    <p><%= link_to "#{task.title}", task_path(task) %></p>
    <p><%= task.details %></p>
    <p><%= link_to "edit", edit_path(task) %></p>
    <p><%= link_to "delete", destroy_path(task), method: :delete %></p>
</div>
  <% end %>
</table>

<%= link_to "create a new task", new_path , class: 'btn' %>

app/views/tasks/new.html.erb
<h1>Add a new task :</h1>

<%= form_for(@task) do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :details %>
  <%= f.text_field :details %>
  </p>

  <p>
  <%= f.label :completed %>
  <%= f.text_field :completed %>

  </p>

<p><%= f.submit %></p>


<% end %>

app/views/tasks/show.html.erb
<h1><%= @one_task.title%></h1>
<ul>
  <li><%= @one_task.details%></li>
  <li><%= @one_task.completed%></li>
</ul>
<%= link_to "Your tasks list !", tasks_path %>